apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image:  {{ index .Values.werf.image "centrifugo" }}
        ports:
        - containerPort: {{ .Values.service.portHttp }}
        resources:
          requests:
            cpu: {{ .Values.limits.cpuRequests }}
            memory: {{ .Values.limits.memoryRequests }}
          limits:
            cpu: {{ .Values.limits.cpuLimits }}
            memory: {{ .Values.limits.memoryLimits }}
      readinessProbe:
        httpGet: { path: /health, port: http }
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet: { path: /health, port: http }
        initialDelaySeconds: 15
        periodSeconds: 20