replicaCount: 1

service:
  name: "frontend"
  portHttp: 3000
ingress:
  enabled: true
  host: freaks-aa.ru
auth:
  clientId: frontend
limits:
  memoryRequests: "500Mi"
  memoryLimits: "1Gi"
  cpuRequests: "500m"
  cpuLimits: "500m"