services:
  portal-web-api:
    image: ${DOCKER_REGISTRY}/portal-web-api:${APP_VERSION}
    build: 
      context: "./dotnet/PortalService"
      dockerfile: "./Dockerfile"
      args:
        - SOLUTION_IMAGE_NAME=${DOCKER_REGISTRY}/solution-build-artifacts:${APP_VERSION}
        - ASPNET_VERSION=${ASPNET_VERSION}
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - KeycloakAdmin__credentials__secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - centrifugo
  files-web-api:
    image: ${DOCKER_REGISTRY}/files-web-api:${APP_VERSION}
    build: 
      context: "./dotnet/FileService"
      dockerfile: "./Dockerfile"
      args:
        - SOLUTION_IMAGE_NAME=${DOCKER_REGISTRY}/solution-build-artifacts:${APP_VERSION}
        - ASPNET_VERSION=${ASPNET_VERSION}
    ports:
      - "5110:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
    depends_on:
      - postgres
      - minio
      - rabbitmq
      - redis
      - centrifugo
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:${POSTGRES_VERSION}
    build: 
      context: "./Postgres"
      dockerfile: "./Dockerfile"
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    ports:
      - "8432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: ${DOCKER_REGISTRY}/minio:${MINIO_VERSION}
    build: 
      context: "./MinIO"
      dockerfile: "./Dockerfile"
      args:
        - MINIO_VERSION=${MINIO_VERSION}
    ports:
      - "11000:9000"
      - "11010:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_CONSOLE_ADDRESS=:9001
    volumes:
      - ./MinIO/data:/data
  rabbitmq:
    image: ${DOCKER_REGISTRY}/rabbitmq:${RABBITMQ_VERSION}
    build: 
      context: "./RabbitMQ"
      dockerfile: "./Dockerfile"
      args:
        - RABBITMQ_VERSION=${RABBITMQ_VERSION}
    ports:
      - "18672:15672"
      - "8672:5672"
      - "8671:5671"
      - "18671:15671"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "9379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  centrifugo:
    image: ${DOCKER_REGISTRY}/centrifugo:${CENTRIFUGO_VERSION}
    build:
      context: "./Centrifugo"
      dockerfile: "./Dockerfile"
      args:
        - CENTRIFUGO_VERSION=${CENTRIFUGO_VERSION}
    command: centrifugo -c config.json
    ports:
      - 8100:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
volumes:
  postgres_data: null
  minio_data: null
  rabbitmq_data: null
