services:
  portal-web-api:
    image: ${DOCKER_REGISTRY}/portal-web-api:${APP_VERSION}
    restart: always
    build: 
      context: "./dotnet/PortalService"
      dockerfile: "./Dockerfile"
      args:
        - SOLUTION_IMAGE_NAME=${DOCKER_REGISTRY}/solution-build-artifacts:${APP_VERSION}
        - ASPNET_VERSION=${ASPNET_VERSION}
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - KeycloakAdmin__resource=realm_admin
      - KeycloakAdmin__credentials__secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
      - DbOptions__ConnectionString=${DB_OPTIONS}
    depends_on:
      - rabbitmq
      - redis
      - centrifugo
  files-web-api:
    image: ${DOCKER_REGISTRY}/files-web-api:${APP_VERSION}
    restart: always
    build: 
      context: "./dotnet/FileService"
      dockerfile: "./Dockerfile"
      args:
        - SOLUTION_IMAGE_NAME=${DOCKER_REGISTRY}/solution-build-artifacts:${APP_VERSION}
        - ASPNET_VERSION=${ASPNET_VERSION}
    ports:
      - "5110:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - DbOptions__ConnectionString=${DB_OPTIONS}
      - StorageOptions__Host=${STORAGE_OPTIONS_HOST}
      - StorageOptions__AccessKey=${STORAGE_OPTIONS_ACCESS_KEY}
      - StorageOptions__SecretKey=${STORAGE_OPTIONS_SECRET_KEY}
      - StorageOptions__DefaultBucketName=${STORAGE_OPTIONS_DEFAULT_BUCKET_NAME}
      - StorageOptions__Region=${STORAGE_OPTIONS_REGION}
      - StorageOptions__WithSsl=${STORAGE_OPTIONS_WITH_SSL}
    depends_on:
      - rabbitmq
      - redis
      - centrifugo
  frontend:
    image: ${DOCKER_REGISTRY}/frontend:${APP_VERSION}
    restart: always
    build:
      context: "./../src/frontend/freaks"
      dockerfile: "./Dockerfile"
      args:
        - NODE_VERSION=node:25-alpine3.23
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=OSQu0Lcij+vgH7VLr7BUtjezVJgLlgzGKHiX/UcNo3w=
      - KEYCLOAK_ID=frontend
  rabbitmq:
    image: ${DOCKER_REGISTRY}/rabbitmq:${RABBITMQ_VERSION}
    restart: always
    build: 
      context: "./RabbitMQ"
      dockerfile: "./Dockerfile"
      args:
        - RABBITMQ_VERSION=${RABBITMQ_VERSION}
    ports:
      - "18672:15672"
      - "8672:5672"
      - "8671:5671"
      - "18671:15671"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - "9379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  centrifugo:
    image: ${DOCKER_REGISTRY}/centrifugo:${CENTRIFUGO_VERSION}
    restart: always
    build:
      context: "./Centrifugo"
      dockerfile: "./Dockerfile"
      args:
        - CENTRIFUGO_VERSION=${CENTRIFUGO_VERSION}
    command: centrifugo -c config.json
    ports:
      - 9000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
volumes:
  postgres_data: null
  minio_data: null
  rabbitmq_data: null
