environment: "Staging"
replicaCount: 2
service:
  name: "centrifugo"
  portHttp: 8000
ingress:
  host: centrifugo.freaks-aa.ru
limits:
  memoryRequests: "256Mi"
  memoryLimits: "256Mi"
  cpuRequests: "250m"
  cpuLimits: "250m"