apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image:  {{ index .Values.werf.image "frontend" }}
          ports:
            - containerPort: {{ .Values.service.portHttp }}
          resources:
            requests:
              cpu: {{ .Values.limits.cpuRequests }}
              memory: {{ .Values.limits.memoryRequests }}
            limits:
              cpu: {{ .Values.limits.cpuLimits }}
              memory: {{ .Values.limits.memoryLimits }}
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: freaks-dev-frontend
                  key: auth_secret
            - name: KEYCLOAK_ID
              value: {{ .Values.auth.clientId }}