// <auto-generated />
using System;
using Freaks.Portal.Dal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freaks.Portal.Dal.Persistence.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20250727051716_added_auction_item_tables")]
    partial class added_auction_item_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Auction.AuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_dt");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTimeOffset>("EndDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_dt");

                    b.Property<int>("LootItemId")
                        .HasColumnType("integer")
                        .HasColumnName("loot_item_id");

                    b.Property<decimal>("MinPriceStep")
                        .HasColumnType("numeric")
                        .HasColumnName("min_price_step");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("start_price");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LootItemId");

                    b.ToTable("auction_item", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Auction.AuctionItemBid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuctionItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("auction_item_id");

                    b.Property<DateTimeOffset>("CreatedDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_dt");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("AuctionItemId");

                    b.HasIndex("CreatorId");

                    b.ToTable("auction_item_bid", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Loot.LootItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_description");

                    b.Property<int>("GradeType")
                        .HasColumnType("integer")
                        .HasColumnName("grade_type");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<int?>("SynthesisExp")
                        .HasColumnType("integer")
                        .HasColumnName("synthesis_exp");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("loot_type");

                    b.HasKey("Id");

                    b.ToTable("loot_item", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.Raid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BossType")
                        .HasColumnType("integer")
                        .HasColumnName("boss_type");

                    b.Property<DateTimeOffset>("CreatedDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_dt");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FormatType")
                        .HasColumnType("integer")
                        .HasColumnName("format_type");

                    b.Property<DateTimeOffset>("StartDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_dt");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_dt");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("raid", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.RaidLoot", b =>
                {
                    b.Property<long>("RaidId")
                        .HasColumnType("bigint")
                        .HasColumnName("raid_id");

                    b.Property<int>("LootItemId")
                        .HasColumnType("integer")
                        .HasColumnName("loot_item_id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("RaidId", "LootItemId");

                    b.HasIndex("LootItemId")
                        .IsUnique();

                    b.ToTable("raid_loot", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.RaidParticipant", b =>
                {
                    b.Property<long>("RaidId")
                        .HasColumnType("bigint")
                        .HasColumnName("raid_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.HasKey("RaidId", "ParticipantId");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("raid_participant", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.RaidScreenshot", b =>
                {
                    b.Property<long>("RaidId")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ScreenshotUrl")
                        .HasColumnType("text")
                        .HasColumnName("screenshot_url");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.HasKey("RaidId", "ScreenshotUrl");

                    b.ToTable("raid_screenshot", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Shop.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int>("LootItemId")
                        .HasColumnType("integer")
                        .HasColumnName("loot_item_id");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_quantity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("total_quantity");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LootItemId");

                    b.ToTable("shop_items", "portal");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Shop.ShopItemRequest", b =>
                {
                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_dt");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("ShopItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("shop_item_requests", "portal");
                });

            modelBuilder.Entity("Freaks.Users.Contracts.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_dt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GameNickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_nickname");

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.Property<DateTimeOffset>("UpdatedDt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_dt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Auction.AuctionItem", b =>
                {
                    b.HasOne("Freaks.Users.Contracts.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freaks.Portal.Contracts.Entities.Loot.LootItem", "LootItem")
                        .WithMany()
                        .HasForeignKey("LootItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("LootItem");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Auction.AuctionItemBid", b =>
                {
                    b.HasOne("Freaks.Portal.Contracts.Entities.Auction.AuctionItem", "Item")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freaks.Users.Contracts.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.Raid", b =>
                {
                    b.HasOne("Freaks.Users.Contracts.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.RaidLoot", b =>
                {
                    b.HasOne("Freaks.Portal.Contracts.Entities.Loot.LootItem", "Loot")
                        .WithOne()
                        .HasForeignKey("Freaks.Portal.Contracts.Entities.RaidSummary.RaidLoot", "LootItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freaks.Portal.Contracts.Entities.RaidSummary.Raid", "Raid")
                        .WithMany("Loots")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loot");

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.RaidParticipant", b =>
                {
                    b.HasOne("Freaks.Users.Contracts.Entities.User", "Participant")
                        .WithOne()
                        .HasForeignKey("Freaks.Portal.Contracts.Entities.RaidSummary.RaidParticipant", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freaks.Portal.Contracts.Entities.RaidSummary.Raid", "Raid")
                        .WithMany("Participants")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.RaidScreenshot", b =>
                {
                    b.HasOne("Freaks.Portal.Contracts.Entities.RaidSummary.Raid", "Raid")
                        .WithMany("Screenshots")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Shop.ShopItem", b =>
                {
                    b.HasOne("Freaks.Users.Contracts.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freaks.Portal.Contracts.Entities.Loot.LootItem", "LootItem")
                        .WithMany()
                        .HasForeignKey("LootItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("LootItem");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Shop.ShopItemRequest", b =>
                {
                    b.HasOne("Freaks.Portal.Contracts.Entities.Shop.ShopItem", "Item")
                        .WithMany("Requests")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freaks.Users.Contracts.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Auction.AuctionItem", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.RaidSummary.Raid", b =>
                {
                    b.Navigation("Loots");

                    b.Navigation("Participants");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("Freaks.Portal.Contracts.Entities.Shop.ShopItem", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
