environment: "Staging"
replicaCount: 1
service:
  name: "files-webapi"
  portHttp: 8080
ingress:
  enabled: true
  host: files-api.freaks-aa.ru
auth:
  issuer: "https://auth.freaks-aa.ru/realms/freaks-dev"
  clientId: "portal-backend"
kcAdmin:
  realm: "freaks-dev"
  authServerUrl: "https://auth.freaks-aa.ru"
  sslRequired: "external"
  resource: "realm_admin"
  verifyTokenAudience: "true"
  confidentialPort: "0"
redis:
  host: "redis-master.freaks-dev.svc.cluster.local"
  port: "6379"
  database: "0"
  connectTimeout: "60000"
  syncTimeout: "60000"
s3:
  serviceUrl: "s3.twcstorage.ru"
  defaultBucketName: "3b49aa04-dfa87595-9ac1-49da-82e3-ebabea7b3c0f"
  withSsl: "true"
limits:
  memoryRequests: "500Mi"
  memoryLimits: "1Gi"
  cpuRequests: "500m"
  cpuLimits: "1000m"
