name: freaks-aa
apiVersion: v2
type: application
appVersion: 1.0.0
dependencies:
  - name: portal-webapi
    export-values:
      - parent: werf
        child: werf
    version: 1.0.0
  - name: files-webapi
    export-values:
      - parent: werf
        child: werf
    version: 1.0.0
  - name: frontend
    export-values:
      - parent: werf
        child: werf
    version: 1.0.0