name: build (werf)

on:
  push:
    branches: ['**']    # предлагать билд на КАЖДЫЙ push, в любую ветку
  workflow_dispatch: {}  # и возможность запустить руками в любой момент

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/werf/werf:2-stable-ubuntu
      options: --security-opt "seccomp:unconfined" --security-opt "apparmor:unconfined" --user 1001
      volumes:
        - buildah-cache:/home/build1001/.local/share/containers
        - werf-cache:/home/build1001/.werf
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: werf build
        shell: bash
        run: |
          . "$(werf ci-env github --as-file)"
          werf build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
