name: staging

on:
  # оставляем push на develop "для вида", но фактически запуск будет только вручную
  push:
    branches: [feat/helm]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: werf-deploy-develop
  cancel-in-progress: true

jobs:
  build:
    name: Build images (werf)
    # запускаем ТОЛЬКО вручную и ТОЛЬКО если ref == develop
    if: ${{ github.event_name == 'workflow_dispatch' && endsWith(github.ref, '/feat/helm') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: werf/actions/install@v2

      - name: werf build
        run: |
          source "$(werf ci-env github --as-file)"
          werf build --env "$WERF_ENV"
        env:
          WERF_ENV: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to staging (werf converge)
    if: ${{ github.event_name == 'workflow_dispatch' && endsWith(github.ref, '/feat/helm') }}
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: werf/actions/install@v2

      - name: werf converge
        run: |
          source "$(werf ci-env github --as-file)"
          werf converge \
            --env "$WERF_ENV" \
            --kube-config-base64 "$WERF_KUBECONFIG_BASE64"
        env:
          WERF_ENV: dev
          WERF_KUBECONFIG_BASE64: ${{ secrets.WERF_KUBECONFIG_BASE64 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
