name: manual build (werf)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/werf/werf:2-stable-ubuntu
      options: --security-opt "seccomp:unconfined" --security-opt "apparmor:unconfined" --user 1001
      volumes:
        - buildah-cache:/home/build1001/.local/share/containers
        - werf-cache:/home/build1001/.werf
    steps:
      - uses: actions/checkout@v4
        with:
          # если ref не задан — чекаутим ветку, выбранную в выпадашке "Use workflow from"
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
          fetch-depth: 0

      - name: werf build
        shell: bash
        run: |
          . "$(werf ci-env github --as-file)"
          werf build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
