name: deploy prod (werf)

on:
  workflow_dispatch: {}

jobs:
  prod:
    runs-on: self-hosted
    container:
      image: ghcr.io/werf/werf:2-stable-ubuntu
      options: --security-opt "seccomp:unconfined" --security-opt "apparmor:unconfined" --user 1001
      volumes:
        - buildah-cache:/home/build1001/.local/share/containers
        - werf-cache:/home/build1001/.werf
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: werf converge
        shell: bash
        run: |
          . "$(werf ci-env github --as-file)"
          werf converge
        env:
          WERF_ENV: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WERF_KUBECONFIG_BASE64: ${{ secrets.WERF_KUBECONFIG_BASE64 }}
