name: manual deploy staging (werf)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch/tag/SHA to deploy (optional)'
        required: false
        type: string

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/werf/werf:2-stable-ubuntu
      options: --security-opt "seccomp:unconfined" --security-opt "apparmor:unconfined" --user 1001
      volumes:
        - buildah-cache:/home/build1001/.local/share/containers
        - werf-cache:/home/build1001/.werf
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
          fetch-depth: 0

      - name: werf converge (staging)
        shell: bash
        run: |
          . "$(werf ci-env github --as-file)"
          werf converge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WERF_KUBE_CONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
